version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - apt-get update -y
      - apt-get install -y wget jq
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - ls -ltrh .
      - echo "sonar.host.url=http://50.17.139.139:9000" >> sonar-scanner-3.3.0.1492-linux/conf/sonar-scanner.properties
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
      - PRNUMBER=$(echo "$CODEBUILD_SOURCE_VERSION" | tr -dc '0-9')
      - SOURCE_BRANCH=$(echo "$CODEBUILD_WEBHOOK_BASE_REF" | sed s/"refs\/heads\/"//)
      - BASE_BRANCH=$(echo "$CODEBUILD_WEBHOOK_HEAD_REF" | sed s/"refs\/heads\/"//)
      - echo $BASE_BRANCH
      - echo $SOURCE_BRANCH
  build:
    commands:
      - ./sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner -Dsonar.login=7217459f076cfccbd99ae0e20eeefcb95be5ab3b -Dsonar.projectKey=slmdeepu2_node_vuln -Dsonar.pullrequest.key=$PRNUMBER -Dsonar.pullrequest.branch=$SOURCE_BRANCH -Dsonar.pullrequest.base=$BASE_BRANCH
